<?php
    return [
        'header_menu' => [
            [
                'label'=>'Characters',
                'href'=>'characters'
            ],
            [
                'label'=>'Comics',
                'href'=>'comics'
            ],
            [
                'label'=>'Movies',
                'href'=>'movies'
            ],
            [
                'label'=>'TV',
                'href'=>'tv'
            ],
            [
                'label'=>'Games',
                'href'=>'games'
            ],
            [
                'label'=>'Collectibles',
                'href'=>'collectibles'
            ],
            [
                'label'=>'Videos',
                'href'=>'videos'
            ],
            [
                'label'=>'Fans',
                'href'=>'fans'
            ],
            [
                'label'=>'News',
                'href'=>'news'
            ],
            [
                'label'=>'Shop',
                'href'=>'shop'
            ]
        ]
    ];
